// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOK.Infrastructure.Persistence.Context;

#nullable disable

namespace SOK.Infrastructure.Migrations.Parish
{
    [DbContext(typeof(ParishDbContext))]
    partial class ParishDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaParishMember", b =>
                {
                    b.Property<int>("AssignedAgendasId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedMembersId")
                        .HasColumnType("int");

                    b.HasKey("AssignedAgendasId", "AssignedMembersId");

                    b.HasIndex("AssignedMembersId");

                    b.ToTable("AgendaParishMember");
                });

            modelBuilder.Entity("ParishMemberPlan", b =>
                {
                    b.Property<int>("ActivePriestsId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedPlansId")
                        .HasColumnType("int");

                    b.HasKey("ActivePriestsId", "AssignedPlansId");

                    b.HasIndex("AssignedPlansId");

                    b.ToTable("ParishMemberPlan");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentLetter")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("BuildingLetter")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FilterableString")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComputedColumnSql("LOWER(CONCAT_WS(' ', COALESCE(StreetType, ''), COALESCE(StreetName, ''), CONCAT(COALESCE(BuildingNumber, ''), COALESCE(BuildingLetter, '')), CONCAT(COALESCE(ApartmentNumber, ''), COALESCE(ApartmentLetter, '')), COALESCE(CityName, '')))", true);

                    b.Property<string>("StreetName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StreetType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FilterableString");

                    b.HasIndex("BuildingId", "ApartmentNumber", "ApartmentLetter")
                        .IsUnique();

                    b.ToTable("Addresses", t =>
                        {
                            t.HasTrigger("TR_Address_InsertOrUpdate_Cache");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValueSql("CONVERT(NVARCHAR(64), HASHBYTES('SHA2_256', CAST(NEWID() AS NVARCHAR(36))), 2)");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndHourOverride")
                        .HasColumnType("time");

                    b.Property<float?>("GatheredFunds")
                        .HasColumnType("real");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowHours")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowsAssignment")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("StartHourOverride")
                        .HasColumnType("time");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowSelection")
                        .HasColumnType("bit");

                    b.Property<int>("ApartmentCount")
                        .HasColumnType("int");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("bit");

                    b.Property<int>("HighestApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreetId", "Number", "Letter")
                        .IsUnique();

                    b.ToTable("Buildings", t =>
                        {
                            t.HasTrigger("TR_Building_Update_AddressCache");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.BuildingAssignment", b =>
                {
                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("DayId", "BuildingId", "ScheduleId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("BuildingAssignments");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Cities", t =>
                        {
                            t.HasTrigger("TR_City_Update_AddressCache");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SenderMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("Sent", "Priority");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StreetSpecifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.ParishInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ParishInfo");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.ParishMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CentralUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CentralUserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DefaultScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DefaultScheduleId")
                        .IsUnique()
                        .HasFilter("[DefaultScheduleId] IS NOT NULL");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Name")
                        .IsUnique();

                    b.HasIndex("PlanId", "ShortName")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("StreetSpecifierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StreetSpecifierId");

                    b.ToTable("Streets", t =>
                        {
                            t.HasTrigger("TR_Street_Update_AddressCache");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.StreetSpecifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("StreetSpecifiers");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValueSql("CONVERT(NVARCHAR(64), HASHBYTES('SHA2_256', CAST(NEWID() AS NVARCHAR(36))), 2)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AdminMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("NotesStatus")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<string>("SubmitterNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SubmitterId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.SubmissionSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AdminMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ChangeAuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("NotesStatus")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StreetSpecifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("SubmitterNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionSnapshots");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Submitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FilterableString")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComputedColumnSql("LOWER(CONCAT_WS(' ', COALESCE(Name, ''), COALESCE(Surname, ''), COALESCE(Name, ''), COALESCE(Email, ''), COALESCE(Phone, '')))", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FilterableString");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Submitters");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.SubmitterSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangeAuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("SubmitterId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("SubmitterId");

                    b.ToTable("SubmitterSnapshots");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("ScheduleId", "OrdinalNumber")
                        .IsUnique()
                        .HasFilter("[ScheduleId] IS NOT NULL AND [OrdinalNumber] IS NOT NULL");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.VisitSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangeAuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DateVisibility")
                        .HasColumnType("bit");

                    b.Property<short>("OrdinalNumber")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly?>("PredictedTime")
                        .HasColumnType("time");

                    b.Property<bool?>("PredictedTimeVisibility")
                        .HasColumnType("bit");

                    b.Property<string>("ScheduleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangeAuthorId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitSnapshots");
                });

            modelBuilder.Entity("AgendaParishMember", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Agenda", null)
                        .WithMany()
                        .HasForeignKey("AssignedAgendasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", null)
                        .WithMany()
                        .HasForeignKey("AssignedMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParishMemberPlan", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", null)
                        .WithMany()
                        .HasForeignKey("ActivePriestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Plan", null)
                        .WithMany()
                        .HasForeignKey("AssignedPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Address", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Building", "Building")
                        .WithMany("Addresses")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Agenda", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Day", "Day")
                        .WithMany("Agendas")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Schedule", null)
                        .WithMany("Agendas")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Building", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Street", "Street")
                        .WithMany("Buildings")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.BuildingAssignment", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Building", "Building")
                        .WithMany("BuildingAssignments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Day", "Day")
                        .WithMany("BuildingAssignments")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Schedule", "Schedule")
                        .WithMany("BuildingAssignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Day");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Day", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Plan", "Plan")
                        .WithMany("Days")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.EmailLog", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Submission", "Submission")
                        .WithMany("EmailLogs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.FormSubmission", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", "Author")
                        .WithMany("EnteredSubmissions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Submission", "Submission")
                        .WithOne("FormSubmission")
                        .HasForeignKey("SOK.Domain.Entities.Parish.FormSubmission", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Plan", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Schedule", "DefaultSchedule")
                        .WithOne()
                        .HasForeignKey("SOK.Domain.Entities.Parish.Plan", "DefaultScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("DefaultSchedule");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Schedule", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Plan", "Plan")
                        .WithMany("Schedules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Street", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.City", "City")
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.StreetSpecifier", "Type")
                        .WithMany()
                        .HasForeignKey("StreetSpecifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Submission", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Address", "Address")
                        .WithOne("Submission")
                        .HasForeignKey("SOK.Domain.Entities.Parish.Submission", "AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Plan", "Plan")
                        .WithMany("Submissions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SOK.Domain.Entities.Parish.Schedule", null)
                        .WithMany("Submissions")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("SOK.Domain.Entities.Parish.Submitter", "Submitter")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Plan");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.SubmissionSnapshot", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Submission", "Submission")
                        .WithMany("History")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeAuthor");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.SubmitterSnapshot", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Submitter", null)
                        .WithMany("History")
                        .HasForeignKey("SubmitterId");

                    b.Navigation("ChangeAuthor");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Visit", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.Agenda", "Agenda")
                        .WithMany("Visits")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Schedule", "Schedule")
                        .WithMany("Visits")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SOK.Domain.Entities.Parish.Submission", "Submission")
                        .WithOne("Visit")
                        .HasForeignKey("SOK.Domain.Entities.Parish.Visit", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Schedule");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.VisitSnapshot", b =>
                {
                    b.HasOne("SOK.Domain.Entities.Parish.ParishMember", "ChangeAuthor")
                        .WithMany()
                        .HasForeignKey("ChangeAuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SOK.Domain.Entities.Parish.Visit", "Visit")
                        .WithMany("History")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeAuthor");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Address", b =>
                {
                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Agenda", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Building", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BuildingAssignments");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Day", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("BuildingAssignments");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.ParishMember", b =>
                {
                    b.Navigation("EnteredSubmissions");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Plan", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Schedules");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Schedule", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("BuildingAssignments");

                    b.Navigation("Submissions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Street", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Submission", b =>
                {
                    b.Navigation("EmailLogs");

                    b.Navigation("FormSubmission")
                        .IsRequired();

                    b.Navigation("History");

                    b.Navigation("Visit")
                        .IsRequired();
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Submitter", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SOK.Domain.Entities.Parish.Visit", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
